sudo: false
dist: trusty
language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - jruby-19mode
  - jruby-head

before_install:
  - '[[ "$(ruby --version)" == *"1.9.3"* ]] && gem update --system 2.4.8 || true'

script:
  - bundle exec rspec -c spec
